main:
  # - identifier: home
  #   name: Accueil
  #   url: /
  #   weight: 10
  - identifier: about
    name: L'association
    url: /about/
    weight: 20
  - identifier: ateliers
    pre: complexdropdown
    name: Ateliers
    weight: 30
  - identifier: mediatheque
    name: Médiathèque
    url: /mediatheque/
    weight: 35
  - identifier: cml
    name: Club Multisports
    url: /club-multisports/
    weight: 37
  - identifier: events
    pre: complexdropdown
    name: Événements
    weight: 40
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 50

ateliers:
  - identifier: yoga
    pre: yoga
    name: Yoga
    post: "Mardi et Jeudi avec Antonine"
    url: /ateliers/yoga/
    weight: 10
  - identifier: pilates
    pre: pilates
    name: Pilates
    post: "Jeudi avec Marie"
    url: /ateliers/pilates/
    weight: 20
  - identifier: gym
    pre: gym
    name: Gym
    post: "Lundi et Mercredi avec Monique"
    url: /ateliers/gym/
    weight: 30
  - identifier: theatre-adultes
    pre: theatre
    name: Théâtre adultes
    post: "Vendredi avec Alain"
    url: /ateliers/theatre-adultes/
    weight: 40
  - identifier: theatre-enfants
    pre: theatre
    name: Théâtre enfants
    post: "Lundi avec Justine"
    url: /ateliers/theatre-enfants/
    weight: 50

events:
  - identifier: hivernale
    pre: vtt # can be stars, comments or piechart
    name: L'hivernale
    post: "Randonnée VTT"
    url: "/evenements/hivernale"
    weight: 10
  - identifier: trail
    pre: running # can be stars, comments or piechart
    name: Lyricantrail
    post: "Course nature de 20km"
    url: "/evenements/lyricantrail"
    weight: 20
  - identifier: festibaleine
    pre: baleine # can be stars, comments or piechart
    name: Festi'Baleine
    post: "Festival de Musique"
    url: "/evenements/baleine"
    weight: 30
  - identifier: triathlon
    pre: triathlon # can be stars, comments or piechart
    name: Triathlon
    post: "Grimpe, VTT, trail"
    url: "/evenements/triathlon"
    weight: 40
  - identifier: conferences
    pre: conference # can be stars, comments or piechart
    name: Conférences
    post: "Ouvertes à tous et toutes"
    url: "/evenements/conferences"
    weight: 50
  - identifier: foire
    pre: plante # can be stars, comments or piechart
    name: Foire aux plantes
    post: "Botanique et vie locale"
    url: "/evenements/foire-aux-plantes"
    weight: 60
  - identifier: vide-grenier
    pre: market # can be stars, comments or piechart
    name: Vide Grenier
    post: "de retour à Larchant"
    url: "/evenements/vide-grenier"
    weight: 70

    
footer:
  - identifier: about
    name: L'association
    url: /about/
    weight: 10
  - identifier: blog
    name: Blog
    url: /categories/blog/
    weight: 20
  - identifier: news
    name: News
    url: /categories/news/
    weight: 30
  - identifier: ateliers
    name: Les ateliers
    url: /ateliers/
    weight: 40
  - identifier: events
    name: Les événements
    url: /evenements/
    weight: 45
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 50

