media:
  input: assets/images
  output: /assets/images

content:
  - name: alaune
    label: "A la Une"
    path: content/news
    type: collection
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Date"
        name: date
        type: datetime
      - label: "Draft"
        name: draft
        type: boolean
        required: false
      - label: "Image"
        name: preview
        type: image
        media_library:
          allow_multiple: false
        required: false
      - label: "Résumé"
        name: summary
        type: text
      - label: "Categorie"
        name: categories
        type: string
        required: false
      - label: "Tags"
        name: tags
        type: string
        required: false
      - label: "Body"
        name: body
        type: markdown
        required: false

  - collection: blog
    label: "Blog"
    folder: content/posts
    create: true
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Date de l'évènement"
        name: date
        type: datetime
      - label: "Draft"
        name: draft
        type: boolean
        required: false
      - label: "Image de présentation"
        name: preview
        type: image
        media_library:
          allow_multiple: false
        media_folder: "/assets/images"
        public_folder: "images"
        required: false
      - label: "Résumé"
        name: summary
        type: text
      - label: "Auteur"
        name: author
        type: string
        required: false
      - label: "Image Auteur"
        name: authorimage
        type: image
        media_library:
          allow_multiple: false
        required: false
      - label: "Categorie"
        name: categories
        type: string
        required: false
      - label: "Tags"
        name: tags
        type: string
        required: false
      - label: "Fichier Joint"
        name: file
        type: file
        required: false
      - label: "Légende du fichier"
        name: file_label
        type: string
        required: false
      - label: "Texte du post"
        name: body
        type: markdown
        required: false

  - collection: ateliers
    label: "Ateliers"
    folder: content/ateliers
    create: true
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Description"
        name: description
        type: string
      - label: "Image"
        name: preview
        type: image
      - label: "Body"
        name: body
        type: markdown

  - collection: activites
    label: "Activités libres"
    folder: content/activites
    create: true
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Description"
        name: description
        type: string
      - label: "Image"
        name: preview
        type: image
      - label: "Body"
        name: body
        type: markdown

  - collection: evenements
    label: "Évènements"
    folder: content/evenements
    create: true
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Description"
        name: description
        type: string
      - label: "Image"
        name: preview
        type: image
      - label: "Body"
        name: body
        type: markdown

  - collection: club-multisports
    label: "Club Multisports"
    folder: content/club-multisports
    create: false
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Description"
        name: description
        type: string
      - label: "Body"
        name: body
        type: markdown

  - collection: mediatheque
    label: "Médiathèque"
    folder: content/mediatheque
    create: false
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Description"
        name: description
        type: string
      - label: "Body"
        name: body
        type: markdown

  - collection: newsletter
    label: "News Mediatheque"
    folder: content/newsletter
    create: true
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Date"
        name: date
        type: datetime
      - label: "Image"
        name: preview
        type: image
        media_library:
          allow_multiple: false
        media_folder: "/assets/images"
        public_folder: "images"
        required: false
      - label: "Categorie"
        name: categories
        type: string
        required: false

  - collection: settings
    label: "Homepage & Settings"
    files:
      - label: "HomePage"
        name: homepage
        file: data/settings.yml
        fields:
          - label: "Slogan"
            name: moto
            type: string
          - label: "Sous-titre"
            name: description
            type: string
          - label: "Bloc de texte 1"
            name: paragraph1
            type: object
            fields:
              - label: "Titre"
                name: heading
                type: string
              - label: "Logo"
                name: image
                type: image
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
          - label: "Bloc de texte 2"
            name: paragraph2
            type: object
            fields:
              - label: "Titre"
                name: heading
                type: string
              - label: "Logo"
                name: image
                type: image
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
          - label: "Bloc Ateliers"
            name: ateliers
            type: object
            fields:
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
              - label: "Liens"
                name: links
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
                  - label: "Lien"
                    name: url
                    type: string
                    hint: "/ateliers"
              - label: "Logos"
                name: logos
                type: list
                fields:
                  - label: "Nom"
                    name: identifier
                    type: string
                  - label: "Image"
                    name: image
                    type: image
                  - label: "Lien"
                    name: url
                    type: string
                    hint: "/ateliers/yoga"
          - label: "Bloc Activités libres"
            name: activities
            type: object
            fields:
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
              - label: "Liens"
                name: links
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
                  - label: "Lien"
                    name: url
                    type: string
                    hint: "/activites"
              - label: "Logos"
                name: logos
                type: list
                fields:
                  - label: "Nom"
                    name: identifier
                    type: string
                  - label: "Image"
                    name: image
                    type: image
          - label: "Bloc News"
            name: blog
            type: object
            fields:
              - label: "Titre"
                name: heading
                type: string
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
          - label: "Formulaire de contact"
            name: mailinglist
            type: object
            fields:
              - label: "Titre"
                name: heading
                type: string
              - label: "Contenu"
                name: content
                type: list
                fields:
                  - label: "Texte"
                    name: text
                    type: text
              - label: "Action"
                name: action
                type: string
                hint: "Ne pas toucher : https://formsubmit.co/quentin.glorieux@gmail.com"
              - label: "Sous-titre"
                name: label
                type: string
              - label: "Remplissage par défaut"
                name: placeholder
                type: string
              - label: "Bouton"
                name: button
                type: string
          - label: "Réseaux sociaux"
            name: social_media
            type: object
            fields:
              - label: "Github"
                name: github
                type: object
                fields:
                  - label: "Activé"
                    name: enabled
                    type: boolean
                  - label: "Lien"
                    name: url
                    type: string
              - label: "Facebook"
                name: facebook
                type: object
                fields:
                  - label: "Activé"
                    name: enabled
                    type: boolean
                  - label: "Lien"
                    name: url
                    type: string
              - label: "Instagram"
                name: instagram
                type: object
                fields:
                  - label: "Activé"
                    name: enabled
                    type: boolean
                  - label: "Lien"
                    name: url
                    type: string
              - label: "Twitter"
                name: twitter
                type: object
                fields:
                  - label: "Activé"
                    name: enabled
                    type: boolean
                  - label: "Lien"
                    name: url
                    type: string

menu:
  main:
    fields:
      - label: "Nom"
        name: name
        type: string
      - label: "Presentation"
        name: pre
        type: select
        options: ["", "complexdropdown"]
        hint: "Choisir complexdropdown pour une sous-collection ou rien pour un menu simple"
        required: false
      - label: "Identifiant"
        name: identifier
        type: string
        required: false
        hint: "Le nom de la collection (ne pas remplir pour complexdropdown)"
      - label: "URL"
        name: url
        type: string
        hint: "Ex: /about/"
