media:
  input: assets/images
  output: /assets/images

content:
  - name: alaune
    label: "A la Une"
    path: content/news
    type: collection
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Date"
        name: date
        type: date
      - label: "Draft"
        name: draft
        type: boolean
        required: false
      - label: "Image"
        name: preview
        type: image
        media_library:
          allow_multiple: false
        required: false
      - label: "Résumé"
        name: summary
        type: text
      - label: "Categorie"
        name: categories
        type: string
        required: false
      - label: "Tags"
        name: tags
        type: string
        required: false
      - label: "Body"
        name: body
        type: rich-text
        required: false

  - type: collection
    name: blog
    label: "Blog"
    path: content/posts
    fields:
      - label: "Titre"
        name: title
        type: string
      - label: "Date de l'évènement"
        name: date
        type: date
      - label: "Draft"
        name: draft
        type: boolean
        required: false
      - label: "Image de présentation"
        name: preview
        type: image
        required: false
      - label: "Résumé"
        name: summary
        type: text
      - label: "Auteur"
        name: author
        type: string
        required: false
      - label: "Image Auteur"
        name: authorimage
        type: image
        required: false
      - label: "Categorie"
        name: categories
        type: string
        required: false
      - label: "Tags"
        name: tags
        type: string
        required: false
      - label: "Fichier Joint"
        name: file
        type: object
        required: false
      - label: "Légende du fichier"
        name: file_label
        type: string
        required: false
      - label: "Texte du post"
        name: body
        type: rich-text
        required: false
