# Domaines temporaires. Noms définitifs : beta.larchantanimation.fr (puis larchantanimation.fr),
# studio.larchantanimation.fr, api.larchantanimation.fr.
server {
  listen 80;
  server_name la.quentinglorieux.fr;
  location / { proxy_pass http://127.0.0.1:13010; include /etc/nginx/proxy_params; }
}
server {
  listen 80;
  server_name studio.la.quentinglorieux.fr;
  client_max_body_size 25m;
  location / { proxy_pass http://127.0.0.1:13011; include /etc/nginx/proxy_params; }
}
server {
  listen 80;
  server_name api.la.quentinglorieux.fr;
  client_max_body_size 25m;
  location / { proxy_pass http://127.0.0.1:18056; include /etc/nginx/proxy_params; }
}
