local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  #  name: github
  #  repo: quentinglorieux/larchant-animation-tailbliss

media_folder: assets/images
public_folder: /images

site_url: http://localhost:1313
display_url: http://localhost:1313
logo_url: http://localhost:1313/assets/images/logo.png

# site_url: https://larchantanimation.fr/
# display_url: https://larchantanimation.fr/
# logo_url: https://larchantanimation.fr/images/logo.png
locale: 'fr'

collections:
  - name: 'content'
    label: 'Pages générales'
    folder: 'content/'
    media_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'alaune'
    label: 'A la Une'
    folder: 'content/news'
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: 'DD/MM/YYYY' }
      - { label: "Draft", name: "draft", widget: "boolean" , required: false}
      - { label: "Image", name: "preview", widget: "image", media_library: { config: { allow_multiple: false } } , required: false}
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Categorie", name: "categories", widget: "string" , required: false}
      - { label: "Tags", name: "tags", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" , required: false}

  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    media_folder: /static/files
    public_folder: /files
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de l'évènement", name: "date", widget: "datetime", format: 'DD/MM/YYYY' }
      - { label: "Draft", name: "draft", widget: "boolean" , required: false}
      - { label: "Image de présentation", name: "preview", widget: "image", media_library: { config: { allow_multiple: false}}, media_folder: '/assets/images', public_folder: 'images'  , required: false}
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Auteur", name: "author", widget: "string" , required: false}
      - { label: "Image Auteur", name: "authorimage", widget: "image", media_library: { config: { allow_multiple: false } } , required: false}
      - { label: "Categorie", name: "categories", widget: "string" , required: false}
      - { label: "Tags", name: "tags", widget: "string", required: false }
      - { label: "Fichier Joint", name: "file", widget: "file" , required: false}
      - { label: "Légende du fichier", name: "file_label", widget: "string" , required: false}
      - { label: "Texte du post", name: "body", widget: "markdown" , required: false}

  - name: 'ateliers'
    label: 'Ateliers'
    folder: '/content/ateliers/'
    path: '/{{slug}}/index'
    media_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'preview', widget: 'image'}
      # - { label: 'Icon', name: 'icon', widget: 'string'}
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'activites'
    label: 'Activités libres'
    folder: '/content/activites/'
    path: '/{{slug}}/index'
    media_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'preview', widget: 'image'}
      # - { label: 'Icon', name: 'icon', widget: 'string'}
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'evenements'
    label: 'Évènements'
    folder: '/content/evenements/'
    path: '/{{slug}}/index'
    media_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'preview', widget: 'image'}
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'club-multisports'
    label: 'Club Multisports'
    folder: 'content/club-multisports/'
    media_folder: ''
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: 'mediatheque'
    label: 'Médiathèque'
    folder: 'content/mediatheque/'
    media_folder: ''
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }





  - label: "Homepage & Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: HomePage
        name: homepage
        file: data/settings.yml
        media_folder: '/static/images/logos/'
        public_folder: '/images/logos'
        fields:
        - { label: Slogan, name: moto, widget: string }
        - { label: Sous-titre, name: description, widget: string }
        - label: Bloc de texte 1
          name: paragraph1
          widget: object
          collapsed: true
          fields: 
          - {label: "Titre", name: "heading", widget: "string"}
          - {label: "Logo", name: "image", widget: "image"}
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
        - label: Bloc de texte 2
          name: paragraph2
          widget: object
          collapsed: true
          fields: 
          - {label: "Titre", name: "heading", widget: "string"}
          - {label: "Logo", name: "image", widget: "image"}
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
        - label: Bloc Ateliers
          name: ateliers
          widget: object
          collapsed: true
          fields:
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
          - label: "Liens"
            name: "links"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
            - { label: Lien, name: url, widget: string, hint: '/ateliers'}
          - label: "Logos"
            name: "logos"
            widget: "list"
            fields:
            - { label: Nom, name: identifier, widget: string}
            - { label: Image, name: image, widget: image}
            - { label: Lien, name: url, widget: string, hint: 'ateliers/yoga'}
        - label: Bloc Activités libres
          name: activities
          widget: object
          collapsed: true
          fields:
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
          - label: "Liens"
            name: "links"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
            - { label: Lien, name: url, widget: string, hint: '/activites'}
          - label: "Logos"
            name: "logos"
            widget: "list"
            fields:
            - { label: Nom, name: identifier, widget: string}
            - { label: Image, name: image, widget: image}
            # - { label: Lien, name: url, widget: string, hint: 'activites/'}
        - label: Bloc News
          name: blog
          widget: object
          collapsed: true
          fields: 
          - {label: "Titre", name: "heading", widget: "string"}
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
        - label: Formulaire de contact
          name: mailinglist
          widget: object
          collapsed: true
          fields: 
          - { label: "Titre", name: "heading", widget: "string"}
          - label: "Contenu"
            name: "content"
            widget: "list"
            fields:
            - { label: Texte, name: text, widget: text}
          - { label: "Action", name: "action", widget: "string", hint: 'Ne pas toucher : https://formsubmit.co/quentin.glorieux@gmail.com'}
          - { label: "Sous-titre", name: "label", widget: "string"}
          - { label: "Remplissage par défaut", name: "placeholder", widget: "string"}
          - { label: "Bouton", name: "button", widget: "string"}
        - label: Réseaux sociaux
          name: social_media
          widget: object
          collapsed: true
          fields: 
          - label: "Github"
            name: "github"
            widget: "object"
            fields:
            - { label: Activé, name: enabled, widget: boolean, required: false}
            - { label: Lien, name: url, widget: string, required: false}
          - label: "Facebook"
            name: "facebook"
            widget: "object"
            fields:
            - { label: Activé, name: enabled, widget: boolean, required: false}
            - { label: Lien, name: url, widget: string, required: false}
          - label: "Instagram"
            name: "instagram"
            widget: "object"
            fields:
            - { label: Activé, name: enabled, widget: boolean, required: false}
            - { label: Lien, name: url, widget: string, required: false}
          - label: "Twitter"
            name: "twitter"
            widget: "object"
            fields:
            - { label: Activé, name: enabled, widget: boolean, required: false}
            - { label: Lien, name: url, widget: string, required: false}



      - label: Menus
        name: menu
        file: config/_default/menu.yml
        media_folder: '/static/images/logos/'
        public_folder: '/images/logos'
        fields:
        - label: Menu Principal
          name: main
          widget: list
          minimize_collapsed: true
          fields:
          - { label: Nom, name: name, widget: 'string' }
          - { label: Presentation, name: pre, widget: 'select', options: ["", "complexdropdown"], hint: 'Choisir complexdropdown pour une sous-collection ou rien pour un menu simple', required: false }
          - { label: Identifiant, name: identifier, widget: 'string', hint: 'Le nom de la collection (ne pas remplir pour complexdropdown)' , required: false}
          - { label: URL, name: url, widget: 'string', hint: 'Ex: /about/' , required: false}
        - label: Ateliers
          name: ateliers
          widget: list
          minimize_collapsed: true
          fields:
            - { label: Nom, name: name, widget: 'string' }
            - { label: Icon, name: pre, widget: 'image' }
            - { label: Sous-titre, name: post, widget: string }
            - { label: Identifiant, name: identifier, widget: 'string', hint: 'Le nom de la collection' }
            - { label: URL, name: url, widget: 'string', hint: 'Ex: /ateliers/gym/'}
        - label: Événements
          name: events
          widget: list
          minimize_collapsed: true  
          fields:
            - { label: Nom, name: name, widget: 'string' }
            - { label: Icon, name: pre, widget: 'image' }
            - { label: Sous-titre, name: post, widget: string }
            - { label: Identifiant, name: identifier, widget: 'string', hint: 'Le nom de la collection' }
            - { label: URL, name: url, widget: 'string', hint: 'Ex: /evenements/vide-grenier'}
        - label: Pied de page
          name: footer
          widget: list
          minimize_collapsed: true
          fields:
          - { label: Nom, name: name, widget: 'string' }
          - { label: Identifiant, name: identifier, widget: 'string', hint: 'Le nom de la collection (ne pas remplir pour complexdropdown)' , required: false}
          - { label: URL, name: url, widget: 'string', hint: 'Ex: /about/' , required: false}
      - label: "Carousel"
        name: "carousel"
        file: "data/carousel.yml"
        media_folder: '/assets/images/'
        public_folder: '/images'
        fields:
          - label: Images
            name: images
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {label: Image, name: image, widget: image}
              - {label: Contenu, name: content_html, widget: string, required: false}



           

